import { BETTER_AUTH_SECRET, BETTER_AUTH_URL, DISCORD_CLIENT_ID, DISCORD_CLIENT_SECRET } from "astro:env/server";

export const env = {
  BETTER_AUTH_SECRET: BETTER_AUTH_SECRET,
  BETTER_AUTH_URL: BETTER_AUTH_URL,
  DISCORD_CLIENT_ID: DISCORD_CLIENT_ID,
  DISCORD_CLIENT_SECRET: DISCORD_CLIENT_SECRET,
} as const;
