import {
  BETTER_AUTH_SECRET,
  BETTER_AUTH_URL,
  DISCORD_CLIENT_ID,
  DISCORD_CLIENT_SECRET,
  DISCORD_ALLOWED_GUILD_ID,
} from "astro:env/server";

export const env = {
  BETTER_AUTH_SECRET,
  BETTER_AUTH_URL,
  DISCORD_ALLOWED_GUILD_ID,
  DISCORD_CLIENT_ID,
  DISCORD_CLIENT_SECRET,
} as const;
