minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeStrict: true
allowBuilds:
  esbuild: false
  lefthook: true
  sharp: false
  unrs-resolver: false
  workerd: true
minimumReleaseAgeExclude:
  # Renovate security update: astro@7.1.0
  - astro@7.1.0
